In [21]:
import pandas as pd
import numpy as np
import re

In [22]:
df = pd.read_csv('subs.csv')

/var/folders/dw/l4h116bs0p1614knym74hj4m0000gn/T/ipykernel_34335/4087030495.py:1: DtypeWarning: Columns (4,6,10,13,16,18,20,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('subs.csv')

In [23]:
file_path = 'subscriptions_60000.csv'

# Specify the delimiter as a semicolon
delimiter = ';'

# Read the CSV file with the header and replace semicolons with commas
df1 = pd.read_csv(file_path, sep=delimiter, on_bad_lines='skip')

# Display the first few rows of the DataFrame
print(df1.head())

         id                     created_at country          operator  \
0   4772183  2023-11-15 01:24:39.890 +0700      ID  id-telkomsel-mks
1   9850460  2023-11-15 22:53:58.779 +0700      ID       telesatpass
2  16139146  2023-11-21 12:28:28.178 +0700      ID  id-telkomsel-mks
3     58769  2023-10-24 02:25:37.089 +0700      ID         telkomsel
4  10936057  2023-11-16 01:54:53.428 +0700      ID         telkomsel

      service source                                             msisdn  \
0  SLYPEE FSC    NaN   SHDC-UIMZr0MUR79HfOsXdjxJBLpYg KxaRHmtGxtc/05qWQ
1    PLAYZONE    sms  SHDC-SE2/sv 8CjW4dwFHjeQrdAaJah6g8F1F mS1LpmkyJQ=
2  SLYPEE DFS    NaN   SHDC-yqSKHCM7crgLi6E45ffYl 1X/6kaAjoFqG 77XO0vd8
3   CLOUDPLAY    WAP  SHDC-n21EFe9DWJPzG/jfTc6e+bXpYIcOgMtQTezeMkaxzXM=
4   CLOUDPLAY    WAP  SHDC-DHR7Jy5mhF4P8zX8lyIHQQ6wb4Kdd7XJDD+MBRpCkB0=

   status  cycle adnet  ...  service_price currency profile_status publisher  \
0       0  daily   NaN  ...           1000      NaN            NaN       NaN
1       1  daily   adg  ...              0      IDR         Active       NaN
2       1  daily   NaN  ...           1000      NaN            NaN       NaN
3       1     2d   adn  ...           2000      IDR         active       NaN
4       1     2d   adn  ...           2000      IDR         active       NaN

                                  trxid pixel  handset browser  \
0                           1,70223E+22   NaN      NaN     NaN
1                           2,02312E+24   NaN      NaN     NaN
2                           10885399605   NaN      NaN     NaN
3  4e28fd8b-15ab-402c-971f-f786a4e9f52f   NaN      NaN     NaN
4  09737f4a-a536-458d-9411-a5be609aacd3   NaN      NaN     NaN

  attempt_charging success_billing
0                1               1
1               35               4
2                6               0
3                1               1
4                1               0

[5 rows x 26 columns]

/var/folders/dw/l4h116bs0p1614knym74hj4m0000gn/T/ipykernel_34335/2027952464.py:7: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(file_path, sep=delimiter, on_bad_lines='skip')

In [5]:
df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57.713,TH,ais,459505104,sms,66988602911,0,daily,NaN,...,6,BATH,Active,NaN,20230913070749401088.0,NaN,NaN,NaN,15,0
1,3521,2023-09-13 09:21:13.679,TH,ais,459505104,sms,66822243080,0,daily,NaN,...,6,BATH,Active,NaN,20230913070724300800.0,NaN,NaN,NaN,15,0
2,1,2023-09-13 09:20:20.727,TH,ais,459505106,ivr,666131,0,1,NaN,...,6,BATH,Active,NaN,20230825140205699072.0,NaN,NaN,NaN,1,1
3,4999335,2023-09-13 14:00:22.171,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,NaN,NaN,5,0
4,273196,2023-09-13 09:45:33.449,TH,ais,459505104,sms,66635959286,0,daily,NaN,...,6,BATH,Active,NaN,20230913070115598336.0,NaN,NaN,NaN,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308906,22019,2023-09-14 06:55:36.464,OM,omantel,goaly,cp1,96898097014,0,daily,kee,...,300,Rial,NaN,lumos,NaN,NaN,/,Apache-HttpClient,1,0
308907,22037,2023-09-14 06:55:36.475,OM,omantel,goaly,cp1,96872209910,0,daily,kee,...,300,Rial,NaN,lumos,NaN,NaN,/,Apache-HttpClient,1,0
308908,22062,2023-09-14 06:55:36.485,OM,omantel,goaly,cp1,96891448321,0,daily,kee,...,300,Rial,NaN,lumos,NaN,NaN,/,Apache-HttpClient,1,0
308909,22083,2023-09-14 06:55:36.498,OM,omantel,goaly,cp1,96891982806,0,daily,kee,...,300,Rial,NaN,lumos,NaN,NaN,/,Apache-HttpClient,1,0
308910,22096,2023-09-14 06:55:36.505,OM,omantel,goaly,cp1,96899008766,0,daily,kee,...,300,Rial,NaN,lumos,NaN,NaN,/,Apache-HttpClient,1,0

In [24]:
total_rows = df.shape[0]
print(f'Total rows in the DataFrame: {total_rows}')

Total rows in the DataFrame: 308911

In [25]:
df1

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,4772183,2023-11-15 01:24:39.890 +0700,ID,id-telkomsel-mks,SLYPEE FSC,NaN,SHDC-UIMZr0MUR79HfOsXdjxJBLpYg KxaRHmtGxtc/05qWQ,0,daily,NaN,...,1000,NaN,NaN,NaN,"1,70223E+22",NaN,NaN,NaN,1,1
1,9850460,2023-11-15 22:53:58.779 +0700,ID,telesatpass,PLAYZONE,sms,SHDC-SE2/sv 8CjW4dwFHjeQrdAaJah6g8F1F mS1LpmkyJQ=,1,daily,adg,...,0,IDR,Active,NaN,"2,02312E+24",NaN,NaN,NaN,35,4
2,16139146,2023-11-21 12:28:28.178 +0700,ID,id-telkomsel-mks,SLYPEE DFS,NaN,SHDC-yqSKHCM7crgLi6E45ffYl 1X/6kaAjoFqG 77XO0vd8,1,daily,NaN,...,1000,NaN,NaN,NaN,10885399605,NaN,NaN,NaN,6,0
3,58769,2023-10-24 02:25:37.089 +0700,ID,telkomsel,CLOUDPLAY,WAP,SHDC-n21EFe9DWJPzG/jfTc6e+bXpYIcOgMtQTezeMkaxzXM=,1,2d,adn,...,2000,IDR,active,NaN,4e28fd8b-15ab-402c-971f-f786a4e9f52f,NaN,NaN,NaN,1,1
4,10936057,2023-11-16 01:54:53.428 +0700,ID,telkomsel,CLOUDPLAY,WAP,SHDC-DHR7Jy5mhF4P8zX8lyIHQQ6wb4Kdd7XJDD+MBRpCkB0=,1,2d,adn,...,2000,IDR,active,NaN,09737f4a-a536-458d-9411-a5be609aacd3,NaN,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56698,97584,"30.20,3",TH,ais,459509903,sms,66808868699,0,daily,NaN,...,6,BATH,Active,NaN,NaN,NaN,NaN,NaN,0,0
56699,384166,"55.22,9",TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,NaN,"2,0231E+19",NaN,NaN,NaN,35,0
56700,27966473,"35.16,7",TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,NaN,ad25621@CPE6:BFHi9IBe,NaN,NaN,NaN,112,14
56701,187009,"37.18,2",TH,ais,459509903,sms,66806582058,0,daily,NaN,...,6,BATH,Active,NaN,NaN,NaN,NaN,NaN,0,0
56702,27906860,"30.21,1",TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,NaN,NaN,NaN,NaN,NaN,0,0

In [26]:
total_rows = df1.shape[0]
print(f'Total rows in the DataFrame: {total_rows}')

Total rows in the DataFrame: 56703

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308911 entries, 0 to 308910
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 308911 non-null  int64
 1   created_at         308911 non-null  object
 2   country            308911 non-null  object
 3   operator           308911 non-null  object
 4   service            308911 non-null  object
 5   source             308307 non-null  object
 6   msisdn             308911 non-null  object
 7   status             308911 non-null  int64
 8   cycle              308911 non-null  object
 9   adnet              147468 non-null  object
 10  revenue            308911 non-null  object
 11  subs_date          308911 non-null  object
 12  renewal_date       308911 non-null  object
 13  freemium_end_date  200000 non-null  object
 14  unsubs_from        63458 non-null   object
 15  unsubs_date        104285 non-null  object
 16  service_price      308911 non-null  object
 17  currency           303190 non-null  object
 18  profile_status     281514 non-null  object
 19  publisher          110947 non-null  object
 20  trxid              120148 non-null  object
 21  pixel              89023 non-null   object
 22  handset            97173 non-null   object
 23  browser            100126 non-null  object
 24  attempt_charging   308911 non-null  int64
 25  success_billing    308911 non-null  int64
dtypes: int64(4), object(22)
memory usage: 61.3+ MB

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56703 entries, 0 to 56702
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 56703 non-null  int64
 1   created_at         56703 non-null  object
 2   country            56703 non-null  object
 3   operator           56703 non-null  object
 4   service            56703 non-null  object
 5   source             46059 non-null  object
 6   msisdn             56703 non-null  object
 7   status             56703 non-null  int64
 8   cycle              56702 non-null  object
 9   adnet              29765 non-null  object
 10  revenue            56703 non-null  int64
 11  subs_date          56703 non-null  object
 12  renewal_date       56670 non-null  object
 13  freemium_end_date  21176 non-null  object
 14  unsubs_from        25529 non-null  object
 15  unsubs_date        33505 non-null  object
 16  service_price      56703 non-null  int64
 17  currency           43959 non-null  object
 18  profile_status     39103 non-null  object
 19  publisher          22364 non-null  object
 20  trxid              32968 non-null  object
 21  pixel              12016 non-null  object
 22  handset            12951 non-null  object
 23  browser            19039 non-null  object
 24  attempt_charging   56703 non-null  int64
 25  success_billing    56703 non-null  int64
dtypes: int64(6), object(20)
memory usage: 11.2+ MB

In [35]:
concatenated_df = pd.concat([df, df1], ignore_index=True)

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57.713,TH,ais,459505104,sms,66988602911,0,daily,NaN,...,6,BATH,Active,NaN,20230913070749401088.0,NaN,NaN,NaN,15,0
1,3521,2023-09-13 09:21:13.679,TH,ais,459505104,sms,66822243080,0,daily,NaN,...,6,BATH,Active,NaN,20230913070724300800.0,NaN,NaN,NaN,15,0
2,1,2023-09-13 09:20:20.727,TH,ais,459505106,ivr,666131,0,1,NaN,...,6,BATH,Active,NaN,20230825140205699072.0,NaN,NaN,NaN,1,1
3,4999335,2023-09-13 14:00:22.171,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,NaN,NaN,5,0
4,273196,2023-09-13 09:45:33.449,TH,ais,459505104,sms,66635959286,0,daily,NaN,...,6,BATH,Active,NaN,20230913070115598336.0,NaN,NaN,NaN,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,"30.20,3",TH,ais,459509903,sms,66808868699,0,daily,NaN,...,6,BATH,Active,NaN,NaN,NaN,NaN,NaN,0,0
365610,384166,"55.22,9",TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,NaN,"2,0231E+19",NaN,NaN,NaN,35,0
365611,27966473,"35.16,7",TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,NaN,ad25621@CPE6:BFHi9IBe,NaN,NaN,NaN,112,14
365612,187009,"37.18,2",TH,ais,459509903,sms,66806582058,0,daily,NaN,...,6,BATH,Active,NaN,NaN,NaN,NaN,NaN,0,0
365613,27906860,"30.21,1",TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,NaN,NaN,NaN,NaN,NaN,0,0

In [36]:
print(type(concatenated_df))

<class 'pandas.core.frame.DataFrame'>

In [37]:
total_rows = concatenated_df.shape[0]
print(f'Total rows in the DataFrame: {total_rows}')

Total rows in the DataFrame: 365614

In [38]:
for column in concatenated_df.columns:
    count = concatenated_df[column].count()
    print(f"Column '{column}' has {count} data points.")

Column 'id' has 365614 data points.
Column 'created_at' has 365614 data points.
Column 'country' has 365614 data points.
Column 'operator' has 365614 data points.
Column 'service' has 365614 data points.
Column 'source' has 354366 data points.
Column 'msisdn' has 365614 data points.
Column 'status' has 365614 data points.
Column 'cycle' has 365613 data points.
Column 'adnet' has 177233 data points.
Column 'revenue' has 365614 data points.
Column 'subs_date' has 365614 data points.
Column 'renewal_date' has 365581 data points.
Column 'freemium_end_date' has 221176 data points.
Column 'unsubs_from' has 88987 data points.
Column 'unsubs_date' has 137790 data points.
Column 'service_price' has 365614 data points.
Column 'currency' has 347149 data points.
Column 'profile_status' has 320617 data points.
Column 'publisher' has 133311 data points.
Column 'trxid' has 153116 data points.
Column 'pixel' has 101039 data points.
Column 'handset' has 110124 data points.
Column 'browser' has 119165 data points.
Column 'attempt_charging' has 365614 data points.
Column 'success_billing' has 365614 data points.

In [39]:
for column in concatenated_df.columns:
    missing_count = df[column].isna().sum()
    total_count = len(df)
    missing_percentage = (missing_count / total_count) * 100
    print(f"Column '{column}' has {missing_percentage:.2f}% missing data points.")

Column 'id' has 0.00% missing data points.
Column 'created_at' has 0.00% missing data points.
Column 'country' has 0.00% missing data points.
Column 'operator' has 0.00% missing data points.
Column 'service' has 0.00% missing data points.
Column 'source' has 0.20% missing data points.
Column 'msisdn' has 0.00% missing data points.
Column 'status' has 0.00% missing data points.
Column 'cycle' has 0.00% missing data points.
Column 'adnet' has 52.26% missing data points.
Column 'revenue' has 0.00% missing data points.
Column 'subs_date' has 0.00% missing data points.
Column 'renewal_date' has 0.00% missing data points.
Column 'freemium_end_date' has 35.26% missing data points.
Column 'unsubs_from' has 79.46% missing data points.
Column 'unsubs_date' has 66.24% missing data points.
Column 'service_price' has 0.00% missing data points.
Column 'currency' has 1.85% missing data points.
Column 'profile_status' has 8.87% missing data points.
Column 'publisher' has 64.08% missing data points.
Column 'trxid' has 61.11% missing data points.
Column 'pixel' has 71.18% missing data points.
Column 'handset' has 68.54% missing data points.
Column 'browser' has 67.59% missing data points.
Column 'attempt_charging' has 0.00% missing data points.
Column 'success_billing' has 0.00% missing data points.

In [40]:
for column in concatenated_df.columns:
    concatenated_df[column] = concatenated_df[column].fillna("not found")

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57.713,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,BATH,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13.679,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,BATH,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20.727,TH,ais,459505106,ivr,666131,0,1,not found,...,6,BATH,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22.171,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33.449,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,BATH,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,"30.20,3",TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365610,384166,"55.22,9",TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,"35.16,7",TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,"37.18,2",TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,"30.21,1",TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,not found,not found,not found,not found,not found,0,0

In [41]:
# Convert 'id' to integer and replace non-integer values with 'NULL'
concatenated_df['id'] = pd.to_numeric(concatenated_df['id'], errors='coerce').fillna('null').astype(int)
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57.713,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,BATH,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13.679,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,BATH,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20.727,TH,ais,459505106,ivr,666131,0,1,not found,...,6,BATH,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22.171,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33.449,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,BATH,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,"30.20,3",TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365610,384166,"55.22,9",TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,"35.16,7",TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,"37.18,2",TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,"30.21,1",TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,not found,not found,not found,not found,not found,0,0

In [42]:
concatenated_df['created_at'] = pd.to_datetime(df['created_at'])
concatenated_df['created_at'] = concatenated_df['created_at'].dt.strftime('%Y-%m-%d %H:%M:%S')
concatenated_df['created_at'] = concatenated_df['created_at'].fillna('not found')

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,BATH,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,BATH,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6,BATH,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,BATH,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,not found,not found,not found,not found,not found,0,0

In [43]:
#revenue
concatenated_df['revenue'] = concatenated_df['revenue'].apply(lambda x: 0 if isinstance(x,str) and ('-' in x or ':' in x) else float(x))
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,BATH,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,BATH,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6,BATH,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,BATH,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,BATH,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,BATH,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,BAHT,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,BATH,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,BAHT,Unsub,not found,not found,not found,not found,not found,0,0

In [44]:
# Currency
concatenated_df['currency'] = concatenated_df['currency'].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,bath,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,bath,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6,bath,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,bath,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,bath,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,bath,Active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,bath,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,baht,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,bath,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,baht,Unsub,not found,not found,not found,not found,not found,0,0

In [45]:
# Operator
concatenated_df['operator'] = concatenated_df['operator'].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6,bath,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6,bath,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6,bath,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6,bath,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6,bath,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6,bath,Active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6,bath,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0,baht,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6,bath,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0,baht,Unsub,not found,not found,not found,not found,not found,0,0

In [46]:
#service_price
concatenated_df['service_price'] = concatenated_df['service_price'].apply(lambda x: 0 if isinstance(x,str) and ('-' in x or ':' in x) else float(x))
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6.0,bath,Active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6.0,bath,Active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6.0,bath,Active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6.0,bath,Active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6.0,bath,Active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6.0,bath,Active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6.0,bath,Active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0.0,baht,Active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6.0,bath,Active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0.0,baht,Unsub,not found,not found,not found,not found,not found,0,0

In [47]:

concatenated_df['subs_date'] = pd.to_datetime(concatenated_df['subs_date'], format='%Y-%m-%d %H:%M:%S.%f', errors='coerce')

# Format the datetime column without timezone information
concatenated_df['subs_date'] = concatenated_df['subs_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

print(concatenated_df['subs_date'].head(100))

0     2022-10-20 19:28:02
1     2020-08-23 16:11:02
2     2023-08-25 14:02:05
3     2023-09-09 13:03:24
4     2022-09-26 19:36:03
             ...
95    2021-12-29 01:18:04
96    2022-01-06 22:05:03
97    2022-10-18 13:13:01
98    2023-01-19 18:42:03
99    2022-09-11 17:35:05
Name: subs_date, Length: 100, dtype: object

In [48]:
concatenated_df['subs_date'] = pd.to_datetime(concatenated_df['subs_date'], errors='coerce')

# Find rows with '9999-01-01' in the time portion
rows_with_9999_time = concatenated_df[concatenated_df['subs_date'].dt.strftime('%H:%M:%S') == '9999-01-01']

# Display the rows with the specified time
print(rows_with_9999_time)

Empty DataFrame
Columns: [id, created_at, country, operator, service, source, msisdn, status, cycle, adnet, revenue, subs_date, renewal_date, freemium_end_date, unsubs_from, unsubs_date, service_price, currency, profile_status, publisher, trxid, pixel, handset, browser, attempt_charging, success_billing]
Index: []

[0 rows x 26 columns]

In [49]:
concatenated_df['renewal_date'] = pd.to_datetime(concatenated_df['renewal_date'], format='%Y-%m-%d %H:%M:%S.%f', errors='coerce')

# Format the datetime column without timezone information
concatenated_df['renewal_date'] = concatenated_df['renewal_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

print(concatenated_df['renewal_date'].head(100))

0     2023-09-14 00:00:00
1     2023-09-14 00:00:00
2     2023-08-26 00:00:00
3     2023-09-14 00:00:00
4     2023-09-14 00:00:00
             ...
95    2023-09-01 00:00:00
96    2023-09-14 00:00:00
97    2023-09-01 00:00:00
98    2023-09-01 00:00:00
99    2023-09-14 00:00:00
Name: renewal_date, Length: 100, dtype: object

In [50]:
concatenated_df['renewal_date'] = pd.to_datetime(concatenated_df['renewal_date'], errors='coerce')

# Find rows with '9999-01-01' in the time portion
rows_with_9999_time = concatenated_df[concatenated_df['renewal_date'].dt.strftime('%H:%M:%S') == '9999-01-01']

# Display the rows with the specified time
print(rows_with_9999_time)

Empty DataFrame
Columns: [id, created_at, country, operator, service, source, msisdn, status, cycle, adnet, revenue, subs_date, renewal_date, freemium_end_date, unsubs_from, unsubs_date, service_price, currency, profile_status, publisher, trxid, pixel, handset, browser, attempt_charging, success_billing]
Index: []

[0 rows x 26 columns]

In [51]:

concatenated_df['freemium_end_date'] = pd.to_datetime(concatenated_df['freemium_end_date'], format='%Y-%m-%d %H:%M:%S.%f', errors='coerce')

# Format the datetime column without timezone information
concatenated_df['freemium_end_date'] = concatenated_df['freemium_end_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

print(concatenated_df['freemium_end_date'].head(100))

0     2022-10-20 00:00:00
1     2020-08-23 00:00:00
2     2023-08-25 00:00:00
3     2023-09-09 00:00:00
4     2022-09-26 00:00:00
             ...
95    2021-12-28 00:00:00
96    2022-01-06 00:00:00
97    2022-10-18 00:00:00
98    2023-01-19 00:00:00
99    2022-09-11 00:00:00
Name: freemium_end_date, Length: 100, dtype: object

In [52]:
concatenated_df['freemium_end_date'] = pd.to_datetime(concatenated_df['freemium_end_date'], errors='coerce')

# Find rows with '9999-01-01' in the time portion
rows_with_9999_time = concatenated_df[concatenated_df['freemium_end_date'].dt.strftime('%H:%M:%S') == '9999-01-01']

# Display the rows with the specified time
print(rows_with_9999_time)

Empty DataFrame
Columns: [id, created_at, country, operator, service, source, msisdn, status, cycle, adnet, revenue, subs_date, renewal_date, freemium_end_date, unsubs_from, unsubs_date, service_price, currency, profile_status, publisher, trxid, pixel, handset, browser, attempt_charging, success_billing]
Index: []

[0 rows x 26 columns]

In [53]:
# profile_status
concatenated_df['profile_status'] = concatenated_df['profile_status'].str.lower()

# Define a list of valid values
valid_unsubs_values = ['active', 'grace', 'parking', 'purging', 'blacklist']

# Replace values that are not in the valid list with 'null'
concatenated_df['profile_status'] = concatenated_df['profile_status'].apply(lambda x: x if x in valid_unsubs_values else 'not found')

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,SMS,66989754515,1,daily,BTM,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,SMS,66822874228,0,daily,BTM,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [54]:
# Source
concatenated_df['source'] = concatenated_df['source'].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,TH,ais,459505104,sms,66988602911,0,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,TH,ais,459505104,sms,66822243080,0,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,TH,ais,459505106,ivr,666131,0,1,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,TH,ais,459505105,wap,66650020857,0,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,TH,ais,459505104,sms,66635959286,0,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,TH,ais,459509903,sms,66808868699,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,TH,ais,459505105,wap,66615676784,1,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,TH,aisgemezz,GE,sms,66989754515,1,daily,BTM,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,TH,ais,459509903,sms,66806582058,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,TH,aisgemezz,GE,sms,66822874228,0,daily,BTM,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [55]:

unique_countries = concatenated_df['country'].unique()

# Display the unique values
print("Unique values in the 'country' column:")
print(unique_countries)

Unique values in the 'country' column:
['TH' 'SN' 'LA' 'OM' 'ID' 'PH']

In [56]:
# Create a mapping of country codes to country names
country_mapping = {
    'TH': 'thailand',
    'OM' : 'oman',
    'LA' : 'laos',
    'SN' : 'senegal',
    'ID' : 'indonesia',
    'PH' : 'philippines'
}

# Replace the country codes with country names
concatenated_df['country'] = concatenated_df['country'].replace(country_mapping)
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,0,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,0,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,0,1,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,0,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,0,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,1,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,GE,sms,66989754515,1,daily,BTM,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,GE,sms,66822874228,0,daily,BTM,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [57]:
# Assuming concatenated_df is your DataFrame
unique_cycle = concatenated_df['cycle'].unique()

# Display the unique values
print("Unique values in the 'cycle' column:")
print(unique_cycle)

Unique values in the 'cycle' column:
['daily' '1' 'weekly' '2d' '3d' 'not found' 'monthly']

In [58]:
concatenated_df['cycle'] = concatenated_df['cycle'].str.lower()


valid_unsubs_values = ['daily', 'weekly', 'monthly', '2d', '3d']


concatenated_df['cycle'] = concatenated_df['cycle'].apply(lambda x: x if x in valid_unsubs_values else 'not found')

In [59]:
# Clean 'publisher' column and convert to lowercase
concatenated_df['publisher'] = concatenated_df['publisher'].str.split('-').str[0].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,0,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,0,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,0,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,0,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,0,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,1,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,GE,sms,66989754515,1,daily,BTM,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,0,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,GE,sms,66822874228,0,daily,BTM,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [60]:
# Assuming concatenated_df is your DataFrame
unique_status = concatenated_df['status'].unique()

# Display the unique values
print("Unique values in the 'status' column:")
print(unique_status)

Unique values in the 'status' column:
[ 0  1 -1  2]

In [61]:
#status
status_mapping = {1: "active, renewed", 0: "active, not renewed", -1: "unsubscribed"}
concatenated_df['status'] = concatenated_df['status'].replace(status_mapping)

concatenated_df['status'] = concatenated_df['status'].apply(lambda x: x if x in valid_unsubs_values else 'not found')

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,GE,sms,66989754515,not found,daily,BTM,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,GE,sms,66822874228,not found,daily,BTM,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [62]:
# Clean 'adnet' column and convert to lowercase
concatenated_df['adnet'] = concatenated_df['adnet'].str.split('-').str[0].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star-APP1694223212644066,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,GE,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,GE,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [63]:
# Clean 'publisher' column and convert to lowercase
concatenated_df['pixel'] = concatenated_df['pixel'].str.split('-').str[0].str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,GE,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,GE,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [64]:
# Assuming concatenated_df is your DataFrame
unique_service = concatenated_df['service'].unique()

# Display the unique values
print("Unique values in the 'service' column:")
print(unique_service)

Unique values in the 'service' column:
[459505104 459505106 459505105 459509902 459509903 459509901 '459505105'
 '459505106' '459505104' '459509903' '459509902' '459509901' 'gemezz'
 'slypee' 'halogame' 'Halogame' 'goaly' 'SLYPEE FSC' 'PLAYZONE'
 'SLYPEE DFS' 'CLOUDPLAY' 'slypee dfs' 'slypee fsc' 'GAMESPOT' 'FUN1'
 'QUIZPRO' 'GAMESC LKT' 'GAZY' 'CLOUDPLAY 1' 'GMSPAZE' 'GALAYS' 'quizy'
 'linguisto' 'omantel' '10291' '10292' '9109' 'GE' 'GEE' 'GED' 'GEA' 'GE7'
 'GEF' 'GE7A' 'GEC' 'GEB' 'GE1']

In [65]:

concatenated_df['service'] = concatenated_df['service'].astype(str).str.lower().str.strip()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,ge,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,ge,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [66]:

unique_service = concatenated_df['service'].unique()

# Display the unique values
print("Unique values in the 'service' column:")
print(unique_service)

Unique values in the 'service' column:
['459505104' '459505106' '459505105' '459509902' '459509903' '459509901'
 'gemezz' 'slypee' 'halogame' 'goaly' 'slypee fsc' 'playzone' 'slypee dfs'
 'cloudplay' 'gamespot' 'fun1' 'quizpro' 'gamesc lkt' 'gazy' 'cloudplay 1'
 'gmspaze' 'galays' 'quizy' 'linguisto' 'omantel' '10291' '10292' '9109'
 'ge' 'gee' 'ged' 'gea' 'ge7' 'gef' 'ge7a' 'gec' 'geb' 'ge1']

In [67]:
# Clean 'attempt_charging' column and ensure it's an integer
concatenated_df['attempt_charging'] = concatenated_df['attempt_charging'].astype(int)
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,ge,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,ge,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [68]:
# Clean 'success_billing' column and ensure it's an integer
concatenated_df['success_billing'] = concatenated_df['success_billing'].astype(int)
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,ge,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,ge,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [69]:
# Clean 'unsubs_from' column by removing "mo_" and making it lowercase
concatenated_df['unsubs_from'] = concatenated_df['unsubs_from'].str.replace('mo_', '').str.lower()
concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,ge,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,ge,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [70]:

unique_unsubs = concatenated_df['unsubs_from'].unique()

# Display the unique values
print("Unique values in the 'unsubs_from' column:")
print(unique_unsubs)

Unique values in the 'unsubs_from' column:
['not found' 'sms' 'ussd' 'portal' 'cstool' 'cctool' 'wap' 'default' 'ivr']

In [71]:
# Define a list of valid values
valid_unsubs_values = ['sms' 'ussd' 'portal' 'cstool' 'cctool' 'wap' 'default' 'ivr']

# Replace values that are not in the valid list with 'null'
concatenated_df['unsubs_from'] = concatenated_df['unsubs_from'].apply(lambda x: x if x in valid_unsubs_values else 'not found')

concatenated_df

,id,created_at,country,operator,service,source,msisdn,status,cycle,adnet,...,service_price,currency,profile_status,publisher,trxid,pixel,handset,browser,attempt_charging,success_billing
0,302164,2023-09-13 09:47:57,thailand,ais,459505104,sms,66988602911,not found,daily,not found,...,6.0,bath,active,not found,20230913070749401088.0,not found,not found,not found,15,0
1,3521,2023-09-13 09:21:13,thailand,ais,459505104,sms,66822243080,not found,daily,not found,...,6.0,bath,active,not found,20230913070724300800.0,not found,not found,not found,15,0
2,1,2023-09-13 09:20:20,thailand,ais,459505106,ivr,666131,not found,not found,not found,...,6.0,bath,active,not found,20230825140205699072.0,not found,not found,not found,1,1
3,4999335,2023-09-13 14:00:22,thailand,ais,459505105,wap,66650020857,not found,daily,star,...,6.0,bath,active,star,20230913071052099584.0,star,not found,not found,5,0
4,273196,2023-09-13 09:45:33,thailand,ais,459505104,sms,66635959286,not found,daily,not found,...,6.0,bath,active,not found,20230913070115598336.0,not found,not found,not found,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365609,97584,not found,thailand,ais,459509903,sms,66808868699,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365610,384166,not found,thailand,ais,459505105,wap,66615676784,not found,daily,mpl,...,6.0,bath,active,not found,"2,0231E+19",not found,not found,not found,35,0
365611,27966473,not found,thailand,aisgemezz,ge,sms,66989754515,not found,daily,btm,...,0.0,baht,active,not found,ad25621@CPE6:BFHi9IBe,not found,not found,not found,112,14
365612,187009,not found,thailand,ais,459509903,sms,66806582058,not found,daily,not found,...,6.0,bath,active,not found,not found,not found,not found,not found,0,0
365613,27906860,not found,thailand,aisgemezz,ge,sms,66822874228,not found,daily,btm,...,0.0,baht,not found,not found,not found,not found,not found,not found,0,0

In [79]:
concatenated_df[concatenated_df['country'] == 'senegal']['currency'].value_counts()

currency
not found    12424
Name: count, dtype: int64